### ISSUE TITLE
Broken logo image on the login screen

### ISSUE THREAD

**Issue by nayonnapurnell** [WriteSpeakCode/writespeakcode.com#34]
### Description
The admin  tries to access the admin portal via http://localhost:8000/admin/#/collections/pages.  Once the admin accesses the login page, the logo image is broken.

### Acceptance Criteria

- [ ] The logo image should appear on the login page.

### Environment

- Operating System: Mac Os Mojave
- Browser: Chrome

### Screenshots
<img width="1131" alt="Screen Shot 2019-05-06 at 9 06 00 PM" src="https://user-images.githubusercontent.com/18585469/57264967-2bb65480-7043-11e9-9ab4-a064b607d6e2.png">

**Comment by deweydell** [comment]
The reason why this is happening is because I used hardcoded link to the image I uploaded to github for the README which contains the words `master` in the url. 

SInce I changed the `master` branch to `production` the link is no longer valid and the correct URL should be: https://raw.githubusercontent.com/WriteSpeakCode/writespeakcode.com/production/src/images/logos/wsc-logo-fullcolor.png

So to fix this issue, we just have to replace the logo URL in the CMS config located at `/static/admin/config.yml`.
